### ISSUE TITLE
about ’ImFusionConsole‘ command

### ISSUE THREAD

**Issue by xieyuexiong** [mfazampour/medphys_ct_us_registration#2]
Hello, I'd like to ask, how do you use the 'ImFusionConsole' command in your code in ‘convert_segmentation_into_mesh.py’? I've already downloaded ImFusionSuite, but I'm not sure how to use it. Looking forward to your reply, thank you！

**Comment by mfazampour** [comment]
Hi, We use the academic installer and we have access to the 'ImFusionConsole' command in the terminal. I am not sure if this is shipped with the free installer as well. please check it on their forum as well: https://forum.imfusion.com
